#! /bin/sh

# Autorun
$HOME/.config/bspwm/autorun.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         1
bspc config focused_border_color "#CC241D"
bspc config normal_border_color "#00000000"
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Godot state=floating
bspc rule -a Gscreenshot state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Gpick state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating
